// <auto-generated />
using ClientRestApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientRestApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240605165651_SetUserIdAsPrimaryKey")]
    partial class SetUserIdAsPrimaryKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClientRestApi.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "fertuionutdragos@yahoo.com",
                            FirstName = "Dragos Ionut",
                            LastName = "Fertu",
                            Password = "Jmek123",
                            PhoneNumber = "0769258202"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "romeofantastik@yahoo.com",
                            FirstName = "Romeo",
                            LastName = "Fantastik",
                            Password = "Crrmrr69",
                            PhoneNumber = "0762413567"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "roserose@yahoo.com",
                            FirstName = "Dragos",
                            LastName = "Pardafir",
                            Password = "Aaaahhhh3",
                            PhoneNumber = "0745667893"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
